### ISSUE TITLE
Error in Acceleration integration

### ISSUE THREAD

**Issue by AnaRhisT94** [makerportal/mpu92-calibration#1]
I'm getting the following error after moving the IMU:
```

python3 accel_integration.py
Starting Data Acquisition
Start Moving IMU...
Data Acquisition Stopped
Traceback (most recent call last):
  File "accel_integration.py", line 189, in <module>
    imu_integrator()
  File "accel_integration.py", line 128, in imu_integrator
    b_filt,a_filt = signal.butter(4,5,'low',fs=Fs_approx)
  File "/home/pi/imu_project/venv/lib/python3.7/site-packages/scipy/signal/filter_design.py", line 2957, in butter
    output=output, ftype='butter', fs=fs)
  File "/home/pi/imu_project/venv/lib/python3.7/site-packages/scipy/signal/filter_design.py", line 2423, in iirfilter
    "must be 0 < Wn < fs/2 (fs={} -> fs/2={})".format(fs, fs/2))
ValueError: Digital filter critical frequencies must be 0 < Wn < fs/2 (fs=6.0 -> fs/2=3.0)

```

Any idea why this happens?

**Comment by AnaRhisT94** [comment]
Solved it by turning off the magnetometer readings which slow my rpi zero. But still the integration fails. (posted in new issue)

**Comment by asciiscry3r** [comment]
Try to downgrade python libs
